# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = whatever.out
SRCS = main.cpp

include ../template.mk

main.cpp: whatever.hpp
