# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = array.out
SRCS = main.cpp

include ../template.mk

main.cpp: Array.hpp
Array.hpp: Array.tpp
